# Identidade do Serviço
spring.application.name=risk-analysis-service
server.port=8082

# Conexão com o Eureka (O GPS)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Força o Eureka a usar o RestTemplate (Nativo do Spring 4)
eureka.client.http-client.type=resttemplate

# Configuração de Logs (Opcional, mas ajuda muito)
logging.level.org.springframework.web=INFO