spring.application.name=transaction-service
server.port=8081

# Conexão com o SEGUNDO banco do Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/db_transactions
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

# Ativa o registro no Eureka
eureka.client.enabled=true
spring.cloud.discovery.enabled=true

# Endereço onde o GPS (Eureka) mora
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Força o Eureka a usar o RestTemplate (nativo) em vez do Jersey
eureka.client.http-client.type=resttemplate