spring.application.name=transaction-service
server.port=8081

# Conexão com o SEGUNDO banco do Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/db_transactions
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

# Desativando Eureka por enquanto para não dar erro no boot
eureka.client.enabled=false
spring.application.name=transaction-service
server.port=8081