server.port=8761
spring.application.name=discovery-server

# O servidor não precisa se registrar nele mesmo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Para vermos o que está acontecendo no log
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF