spring.application.name=account-service

# Conexão com o banco específico de contas
spring.datasource.url=jdbc:postgresql://localhost:5431/db_accounts
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ativa o registro no Eureka
eureka.client.enabled=true
spring.cloud.discovery.enabled=true

# Endereço onde o GPS (Eureka) mora
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Força o Eureka a usar o RestTemplate (nativo) em vez do Jersey
eureka.client.http-client.type=resttemplate